version: "3.4"
services:
  postgres:
    image: postgres:alpine
    networks:
      - net
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./packages/service-nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    depends_on:
      - node-main
  node-main:
    build:
      target: production
      context: .
      dockerfile: ./node-package.Dockerfile
      args:
        - PACKAGE_NAME=node-main
    container_name: node-main
    command: yarn run server
    networks:
      - net
    depends_on:
      - node-renderer
      - node-graphql
  node-graphql:
    build:
      target: production
      context: .
      dockerfile: ./node-package.Dockerfile
      args:
        - PACKAGE_NAME=node-graphql
    container_name: node-graphql
    command: yarn run server
    networks:
      - net
    depends_on:
      - postgres
  node-renderer:
    build:
      target: production
      context: .
      dockerfile: ./packages/node-renderer/Dockerfile
    container_name: node-renderer
    command: yarn start
    networks:
      - net

volumes:
  yarn-cache:

networks:
  net:
    driver: bridge
