export * from './Housing';
export * from './Cathedra';
export * from './Classroom';
export * from './Faculty';
export * from './Speciality';
export * from './Group';
export * from './Worker';
export * from './Lesson';
export * from './User';
